import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedmenusuperiorwidget5/generated/GeneratedMenuWidget5.dart';

/* Component Menu superior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenusuperiorWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 110.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 187.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: GeneratedMenuWidget5(),
              )
            ]),
      ),
    ));
  }
}
