import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedbriefcasesharpwidget/generated/GeneratedVectorWidget93.dart';

/* Frame briefcase-sharp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBriefcasesharpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 25.0,
        height: 25.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.7812463641166687,
                top: 2.34375,
                right: null,
                bottom: null,
                width: 23.437503814697266,
                height: 20.3125,
                child: GeneratedVectorWidget93(),
              )
            ]),
      ),
    ));
  }
}
