import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup30widget/generated/GeneratedRectangle17Widget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup30widget/generated/GeneratedInformationcirclesharpWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup30widget/generated/GeneratedEditarinformaciondelusuarioWidget2.dart';

/* Component Group 30
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup30Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle17Widget2(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedInformationcirclesharpWidget2(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 246.0,
              height: 25.0,
              child: GeneratedEditarinformaciondelusuarioWidget2(),
            )
          ]),
    ));
  }
}
