import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedimagendeordenwidget1/generated/GeneratedRectangle9Widget4.dart';

/* Component Imagen de orden
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImagendeordenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 350.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 350.0,
              child: GeneratedRectangle9Widget4(),
            )
          ]),
    ));
  }
}
