import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedframe2widget/generated/GeneratedChevronbackWidget2.dart';

/* Component Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 100.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 18.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedChevronbackWidget2(),
              )
            ]),
      ),
    ));
  }
}
