import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup31widget/generated/GeneratedPricetagsWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup31widget/generated/GeneratedPromocionesWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup31widget/generated/GeneratedRectangle16Widget2.dart';

/* Component Group 31
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup31Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle16Widget2(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPricetagsWidget2(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 134.0,
              height: 33.0,
              child: GeneratedPromocionesWidget2(),
            )
          ]),
    ));
  }
}
