import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup33widget/generated/GeneratedCardWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup33widget/generated/GeneratedMetododepagoWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup33widget/generated/GeneratedRectangle14Widget2.dart';

/* Component Group 33
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup33Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle14Widget2(),
            ),
            Positioned(
              left: 14.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedCardWidget2(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 166.0,
              height: 30.0,
              child: GeneratedMetododepagoWidget2(),
            )
          ]),
    ));
  }
}
