import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedOtrasopcionesWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedUbicacionesguardadasWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedTrabajoWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedAgregaladirecciondetutrabajoWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedCallePicachos2011Widget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedConfiguracionWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedCerrarSesionWidget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedMenusuperiorWidget4.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/pizzasapp/generatedajusteswidget10/generated/GeneratedCasaWidget.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget4(),
              ),
              Positioned(
                left: 157.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 25.0,
                child: GeneratedConfiguracionWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 674.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 163.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 217.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 30.0,
                child: GeneratedUbicacionesguardadasWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 30.0,
                child: GeneratedCasaWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 30.0,
                child: GeneratedTrabajoWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 17.0,
                child: GeneratedCallePicachos2011Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 17.0,
                child: GeneratedAgregaladirecciondetutrabajoWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 37.0,
                child: GeneratedOtrasopcionesWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 30.0,
                child: GeneratedCerrarSesionWidget(),
              )
            ]),
      ),
    ));
  }
}
