import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup34widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedgroup34widget/generated/GeneratedStarWidget1.dart';
import 'package:flutterapp/pizzasapp/generatedgroup34widget/generated/GeneratedRecompensasWidget1.dart';

/* Component Group 34
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup34Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle13Widget1(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedStarWidget1(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 147.0,
              height: 33.0,
              child: GeneratedRecompensasWidget1(),
            )
          ]),
    ));
  }
}
