import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup38widget/generated/GeneratedEditarinformaciondelusuarioWidget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup38widget/generated/GeneratedRectangle17Widget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup38widget/generated/GeneratedInformationcirclesharpWidget3.dart';

/* Instance Group 38
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup38Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle17Widget3(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedInformationcirclesharpWidget3(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 143.0,
              height: 25.0,
              child: GeneratedEditarinformaciondelusuarioWidget3(),
            )
          ]),
    ));
  }
}
