import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedEllipse2Widget4.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedPizzaWidget4.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/Generated\$6999Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedFrame1Widget4.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedVectorWidget76.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedAgotadaWidget4.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedHeartoutlineWidget4.dart';
import 'package:flutterapp/pizzasapp/generatedpizzaswidget1/generated/GeneratedRectangle5Widget4.dart';

/* Component Pizzas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPizzasWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 380.0,
      height: 200.0,
      decoration: BoxDecoration(
        border: Border.all(
          width: 1.0,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 380.0,
              height: 200.0,
              child: GeneratedRectangle5Widget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 380.0,
              height: 200.0,
              child: GeneratedRectangle7Widget5(),
            ),
            Positioned(
              left: 17.0,
              top: 28.0,
              right: null,
              bottom: null,
              width: 94.0,
              height: 24.0,
              child: GeneratedFrame1Widget4(),
            ),
            Positioned(
              left: 27.0,
              top: 35.0,
              right: null,
              bottom: null,
              width: 10.0,
              height: 10.0,
              child: GeneratedEllipse2Widget4(),
            ),
            Positioned(
              left: 41.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 65.0,
              height: 20.0,
              child: GeneratedAgotadaWidget4(),
            ),
            Positioned(
              left: 10.0,
              top: 150.0,
              right: null,
              bottom: null,
              width: 47.0,
              height: 25.0,
              child: GeneratedPizzaWidget4(),
            ),
            Positioned(
              left: 272.0,
              top: 164.0,
              right: null,
              bottom: null,
              width: 96.0,
              height: 40.0,
              child: Generated$6999Widget1(),
            ),
            Positioned(
              left: 27.0,
              top: 172.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedHeartoutlineWidget4(),
            ),
            Positioned(
              left: 17.0,
              top: 175.0,
              right: null,
              bottom: null,
              width: 15.000792503356934,
              height: 13.750049591064453,
              child: GeneratedVectorWidget76(),
            )
          ]),
    ));
  }
}
