import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/pizzasapp/generatedframe4widget/generated/GeneratedCameraWidget.dart';
import 'package:flutterapp/pizzasapp/generatedframe4widget/generated/GeneratedElegirdegaleriaWidget.dart';
import 'package:flutterapp/pizzasapp/generatedframe4widget/generated/GeneratedImageWidget.dart';
import 'package:flutterapp/pizzasapp/generatedframe4widget/generated/GeneratedTomarfotoWidget.dart';

/* Component Frame 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(12, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(10.0),
        child: Container(
          width: 179.0,
          height: 80.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10.0),
            border: Border.all(
              width: 0.5,
              color: Color.fromARGB(255, 149, 149, 149),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(10.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 42.0,
                  top: 14.0,
                  right: null,
                  bottom: null,
                  width: 91.0,
                  height: 25.0,
                  child: GeneratedTomarfotoWidget(),
                ),
                Positioned(
                  left: 42.0,
                  top: 42.0,
                  right: null,
                  bottom: null,
                  width: 134.0,
                  height: 25.0,
                  child: GeneratedElegirdegaleriaWidget(),
                ),
                Positioned(
                  left: 17.0,
                  top: 14.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedCameraWidget(),
                ),
                Positioned(
                  left: 17.0,
                  top: 44.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedImageWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
