import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup35widget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup35widget/generated/GeneratedMetododepagoWidget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup35widget/generated/GeneratedCardWidget3.dart';

/* Instance Group 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup35Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle14Widget3(),
            ),
            Positioned(
              left: 14.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedCardWidget3(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 166.0,
              height: 30.0,
              child: GeneratedMetododepagoWidget3(),
            )
          ]),
    ));
  }
}
