import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedMenuinferiorWidget1.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedProximospedidosWidget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedMenusuperiorWidget1.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget2/generated/GeneratedFrame5Widget.dart';

/* Frame Pedidos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPedidosWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 80.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 139.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 22.0,
                child: GeneratedProximospedidosWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 80.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 200.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 200.0,
                child: GeneratedRectangle8Widget(),
              )
            ]),
      ),
    ));
  }
}
