import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generateddetalledelaordenwidget/generated/GeneratedImagendeordenWidget.dart';
import 'package:flutterapp/pizzasapp/generateddetalledelaordenwidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/pizzasapp/generateddetalledelaordenwidget/generated/GeneratedDetallesWidget.dart';
import 'package:flutterapp/pizzasapp/generateddetalledelaordenwidget/generated/GeneratedMenuinferiorWidget3.dart';

/* Frame Detalle de la Orden
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetalledelaOrdenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 350.0,
                child: GeneratedImagendeordenWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 100.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 523.0,
                child: GeneratedDetallesWidget(),
              )
            ]),
      ),
    ));
  }
}
