import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatediniciowidget/generated/GeneratedMenuinferiorWidget.dart';
import 'package:flutterapp/pizzasapp/generatediniciowidget/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/pizzasapp/generatediniciowidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/pizzasapp/generatediniciowidget/generated/GeneratedPropiedadWidget.dart';
import 'package:flutterapp/pizzasapp/generatediniciowidget/generated/GeneratedMenusuperiorWidget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 60.0,
                child: GeneratedBuscadorWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 200.0,
                child: GeneratedPropiedadWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 200.0,
                child: GeneratedRectangle6Widget(),
              )
            ]),
      ),
    ));
  }
}
