import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup36widget/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup36widget/generated/GeneratedAyudaWidget3.dart';
import 'package:flutterapp/pizzasapp/generatedgroup36widget/generated/GeneratedHelpcircleWidget3.dart';

/* Instance Group 36
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup36Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle15Widget3(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedHelpcircleWidget3(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 33.0,
              child: GeneratedAyudaWidget3(),
            )
          ]),
    ));
  }
}
