import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedNohaypedidosprogramadosWidget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedCalendarsharpWidget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedPedidosProgramadosWidget.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedMenusuperiorWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedFrame5Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedpedidoswidget5/generated/GeneratedMenuinferiorWidget2.dart';

/* Frame Pedidos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPedidosWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 112.0,
                child: GeneratedMenuinferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 33.0,
                child: GeneratedNohaypedidosprogramadosWidget(),
              ),
              Positioned(
                left: 166.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedCalendarsharpWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 22.0,
                child: GeneratedPedidosProgramadosWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 93.0,
                child: GeneratedFrame5Widget1(),
              )
            ]),
      ),
    ));
  }
}
