import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedgroup32widget/generated/GeneratedHelpcircleWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup32widget/generated/GeneratedAyudaWidget2.dart';
import 'package:flutterapp/pizzasapp/generatedgroup32widget/generated/GeneratedRectangle15Widget2.dart';

/* Component Group 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 355.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 60.0,
              child: GeneratedRectangle15Widget2(),
            ),
            Positioned(
              left: 14.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedHelpcircleWidget2(),
            ),
            Positioned(
              left: 53.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 33.0,
              child: GeneratedAyudaWidget2(),
            )
          ]),
    ));
  }
}
