import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedportraitwidget1/generated/GeneratedGroup28Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedportraitwidget1/generated/GeneratedGroup27Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedportraitwidget1/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/pizzasapp/generatedportraitwidget1/generated/GeneratedGroup29Widget1.dart';

/* Component Portrait
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPortraitWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 100.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 100.0,
              child: GeneratedRectangle11Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 117.0,
              height: 117.0,
              child: GeneratedGroup27Widget1(),
            ),
            Positioned(
              left: 120.0,
              top: 23.0,
              right: null,
              bottom: null,
              width: 167.0,
              height: 44.0,
              child: GeneratedGroup29Widget1(),
            ),
            Positioned(
              left: 79.0,
              top: 83.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 33.0,
              child: GeneratedGroup28Widget1(),
            )
          ]),
    ));
  }
}
