import 'package:flutter/material.dart';
import 'package:flutterapp/pizzasapp/generatedhomesharpwidget/generated/GeneratedVectorWidget92.dart';

/* Frame home-sharp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomesharpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 25.0,
        height: 25.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 1.5625,
                right: null,
                bottom: null,
                width: 25.0,
                height: 21.875,
                child: GeneratedVectorWidget92(),
              )
            ]),
      ),
    ));
  }
}
